### ISSUE TITLE
Move or attack selection

### ISSUE THREAD

**Issue by Quarz8** [Quarz8/chess-4a#8]
Currently there is no way to tell a piece to move or attack properly. These actions are not linked together as they are in traditional chess, so there needs to be a way for players to choose which action they wish to take.

Not sure if this would be best done with more buttons or what, but it needs to be done.

The knight being able to both move and attack in one action could raise further complications, but perhaps that is outside the scope of this issue.

**Comment by scrowley0** [comment]
Reopened for implementation

**Comment by Quarz8** [comment]
Attacking and moving is now contextual, no longer need buttons
